AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: BraidsByVee booking API (API Gateway + Lambda + DynamoDB)

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 256

Resources:
  BookingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BraidsByVeeBookings
      AttributeDefinitions:
        - AttributeName: bookingId
          AttributeType: S
      KeySchema:
        - AttributeName: bookingId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  BookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/lambda-example/
      Handler: index.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref BookingTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookingTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /book
            Method: POST

Outputs:
  ApiEndpoint:
    Description: Invoke URL for POST /book
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/book"
